[package]
name = "content"
version = "0.0.0"
edition = "2021"

[dependencies]
delaunator = "1.0.2"
engine = { path = "../engine" }
nalgebra-glm = "0.18.0"
pathfinding = "4.3.0"
profiling = { version = "1.0.8", features = ["puffin", "profile-with-puffin"] }
rand = "0.8.5"
