[workspace]
members = ["crates/*"]
resolver = "2"

[profile.dev]
debug = 2
debug-assertions = true
overflow-checks = true

[profile.release]
debug = 1
opt-level = 3
overflow-checks = false
strip = "debuginfo"
lto = "fat"
